#!/usr/bin/perl

### BEGIN INIT INFO
# Provides:          ubic-ping
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ubic ping service
# Description:       ubic-ping allows to get service status using http
### END INIT INFO

use Ubic::Run;
